version: "3.8"

services:
    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        container_name: composer
        # command: ["composer", "install"]
        # volumes:
        # depends_on:

    symfony:
        build:
            context: dockerfiles
            dockerfile: symfony.Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - '/app:/app'
    
    db:
        build:
            context: dockerfiles
            dockerfile: postgres.Dockerfile
        container_name: db
        ports:
            - "5432"
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./sql:/sql
            - db-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - "8080:8080"
volumes:
  db-data: